### ISSUE TITLE
Endepunkt API-katalogen

### ISSUE THREAD

**Issue by thorejoa** [Informasjonsforvaltning/dsop-api-spesifikasjoner#10]
Er det mulighet for å få opp igjen den gamle URLen i en overgangsperiode? Politiet, som benytter Kontrollinformasjon, har et strengt regime for å åpne for nye URL'er i brannmursåpningen og det vil ta over et par måneder før de får lagt inn ny URL.

Det hjalp dem heller ikke at det ble opprettet en redirect-url i og med at den går til det nye endepunktet.

**Comment by stigbd** [comment]
Midlertidig løysing: Vi har oppretta ein reverse-proxy for som Politiet kan nytte til dei får lagt inn den nye url i sine systemer. Dermed vil den gamle url fungere som før.
