### ISSUE TITLE
Endring av test-endepunkt for DNB i API-katalogen

### ISSUE THREAD

**Issue by astridbits** [Informasjonsforvaltning/dsop-api-spesifikasjoner#100]
Hei,
DNB har endret endepunkts-URL i test til https://test.publicsector.dnb.no/v2 som skal registreres i API-katalogen

Org. nr.: 984 851 006
Navn: DNB Bank ASA
Nytt endepunkt test: https://test.publicsector.dnb.no/v2

**Comment by valosnah** [comment]
@astridbits Da er det oppdatert!
https://demo.fellesdatakatalog.digdir.no/data-services/23702115-5305-3778-a85a-a9d997d9f9cc
