### ISSUE TITLE
Endring av test-endepunkter for Sparebank1 i API-katalogen

### ISSUE THREAD

**Issue by astridbits** [Informasjonsforvaltning/dsop-api-spesifikasjoner#104]
Hei,

Følgende endringer av endepunkts-URLer i test skal registreres i API-katalogen for Sparebank1 bankene:

orgNo: 937899408
url: https://api-test.sparebank1.no/dsopaccountcontrolinfo/AccountControlInfoService/v2_0/937899408
 
orgNo: 937891334
url: https://api-test.sparebank1.no/dsopaccountcontrolinfo/AccountControlInfoService/v2_0/937891334
 
orgNo: 937889631
url: https://api-test.sparebank1.no/dsopaccountcontrolinfo/AccountControlInfoService/v2_0/937889631
 
orgNo: 937888104
url: https://api-test.sparebank1.no/dsopaccountcontrolinfo/AccountControlInfoService/v2_0/937888104
 
orgNo: 937901003
url: https://api-test.sparebank1.no/dsopaccountcontrolinfo/AccountControlInfoService/v2_0/937901003
 
orgNo: 920426530
url: https://api-test.sparebank1.no/dsopaccountcontrolinfo/AccountControlInfoService/v2_0/920426530
 
orgNo: 937888015
url: https://api-test.sparebank1.no/dsopaccountcontrolinfo/AccountControlInfoService/v2_0/937888015
 
orgNo: 952706365
url: https://api-test.sparebank1.no/dsopaccountcontrolinfo/AccountControlInfoService/v2_0/952706365
 
orgNo: 937889186
url: https://api-test.sparebank1.no/dsopaccountcontrolinfo/AccountControlInfoService/v2_0/937889186
 
orgNo: 975966453
url: https://api-test.sparebank1.no/dsopaccountcontrolinfo/AccountControlInfoService/v2_0/975966453
 
orgNo: 944521836
url: https://api-test.sparebank1.no/dsopaccountcontrolinfo/AccountControlInfoService/v2_0/944521836
 
orgNo: 837884942
url: https://api-test.sparebank1.no/dsopaccountcontrolinfo/AccountControlInfoService/v2_0/837884942
 
orgNo: 937889275
url: https://api-test.sparebank1.no/dsopaccountcontrolinfo/AccountControlInfoService/v2_0/937889275

**Comment by hegeaal** [comment]
@astridbits Da skal det være oppdatert ☺️
