### ISSUE TITLE
Nytt navn: Rogaland Sparebank (Sandnes Sparebank og Hjelmeland Sparebank)

### ISSUE THREAD

**Issue by niddaaslam** [Informasjonsforvaltning/dsop-api-spesifikasjoner#109]
Hei,

Hjelmeland Sparebank har fusjonert med Sandnes Sparebank.
Sandnes Sparebank er overtakende bank og har nå endret navn til Rogaland Sparebank.
Navnet i API-katalogen skal endres fra Sandnes Sparebank til Rogaland Sparebank

**Comment by niddaaslam** [comment]
Endepunktet for Hjelmeland Sparebank ble avsluttet i teknisk fusjonshelg 7-8 september.

**Comment by NilsOveTen** [comment]
@niddaaslam Nå har det blitt oppdatert: https://data.norge.no/data-services/052792f7-16f1-3512-8df3-0af8e400c868
