### ISSUE TITLE
Endepunkt for Bluestep Bank AB Filial Oslo i testmiljø

### ISSUE THREAD

**Issue by tonjelund** [Informasjonsforvaltning/dsop-api-spesifikasjoner#12]
Hei,

Kan dere registrere følgende endepunkt for Bluestep Bank AB Filial Oslo - org.nr 995268841 i testmiljø?
https://api-test.bluestep.se/koko/api/v1

**Comment by stigbd** [comment]
Utført i 463c9272cd33093503e112ce0722515bbd88967a
