### ISSUE TITLE
Endepunkt for Ekspress Bank i testmiljø

### ISSUE THREAD

**Issue by tonjelund** [Informasjonsforvaltning/dsop-api-spesifikasjoner#13]
Hei,

Kan dere registrere endepunkt for Ekspress Bank - org.nr 991 682 511 i testmiljø?
https://apigateway.preprod.expressbank.dk/control-information/v1

**Comment by stigbd** [comment]
Utført i 463c9272cd33093503e112ce0722515bbd88967a
