### ISSUE TITLE
Endepunkt for Nordax Bank AB (publ) i testmiljø

### ISSUE THREAD

**Issue by tonjelund** [Informasjonsforvaltning/dsop-api-spesifikasjoner#14]
Hei,

Kan dere registrere endepunkt for Nordax Bank AB (publ) - org.nr 916 573 154 i testmiljø?
https://partner.preprod.nordax.com/DSOP/v1

**Comment by stigbd** [comment]
Utført i 463c9272cd33093503e112ce0722515bbd88967a
