### ISSUE TITLE
Endepunkt for Komplett Bank ASA i produksjonsmiljø

### ISSUE THREAD

**Issue by thorejoa** [Informasjonsforvaltning/dsop-api-spesifikasjoner#15]
Hei,

Kan dere registrere følgende endepunkt for Komplett Bank ASA – 998997801 i produksjonsmiljø?:
https://eoppslag.online.komplettbank.no/v1

**Comment by thorejoa** [comment]
@stigbd Har dere en status på denne?

**Comment by stigbd** [comment]
Produksjonsendepunktet er lagt inn i spesifikasjonen no. Closer issue når det blir tilgjengelig i API-et. (I løpet av dagen.)

**Comment by stigbd** [comment]
Då er produksjonsendepunktet i registrert og tilgjengelig:
https://fellesdatakatalog.digdir.no/apis/3c174c4a-e520-4ddf-842c-2587db07e260
