### ISSUE TITLE
Endepunkt for Ekspress Bank i produksjonsmiljø

### ISSUE THREAD

**Issue by tonjelund** [Informasjonsforvaltning/dsop-api-spesifikasjoner#16]
Hei,
Kan dere tilgjengeliggjøre endepunktet for Ekspress Bank - 991682511 i produksjonsmiljø?
https://apigateway.expressbank.dk/control-information/v1

**Comment by stigbd** [comment]
Produksjonsendepunkt er lagt til i c64689e19ffb680e1158c39b7f113acf244f1284

Det vil bli tilgjengeliggjort i løpet av kort tid.

**Comment by stigbd** [comment]
Produksjonsendepunktet er no verifisert tilgjengeleg, ref https://fellesdatakatalog.digdir.no/apis/d5249507-7fd7-4ebe-bed7-5218d82937ca
