### ISSUE TITLE
 Endepunkt for BRAbank ASA i testmiljø. 

### ISSUE THREAD

**Issue by Unn-Merete** [Informasjonsforvaltning/dsop-api-spesifikasjoner#17]
Hei,

Kan dere registrere endepunkt for BRAbank ASA - org.nr 913460715 i testmiljø?
https://externalcontrolapi.bralabs.no/

Mvh
Unn-Merete

**Comment by Unn-Merete** [comment]
Hei igjen, 
En liten korreksjon på endepunktet i forrige melding. Det skal legges til v1 på slutten av endepunktet. Slik at det blir https://externalcontrolapi.bralabs.no/v1

**Comment by stigbd** [comment]
Ok, test-endepunktet til BRAbank er no publisert før eg såg korreksjonen:
https://fellesdatakatalog.digdir.no/apis/a43bc845-92e7-4e60-8d9b-f4dfeedd55d6

Eg skal endre til korrekt url no.

**Comment by stigbd** [comment]
Er korrekt no:
https://fellesdatakatalog.digdir.no/apis/a43bc845-92e7-4e60-8d9b-f4dfeedd55d6
