### ISSUE TITLE
Endepunkt for NORDAX BANK AB (PUBL) i produksjonsmiljø

### ISSUE THREAD

**Issue by thorejoa** [Informasjonsforvaltning/dsop-api-spesifikasjoner#18]
Kan dere registrere endepunktet for NORDAX BANK AB (PUBL) - 916573154 i produksjonsmiljø?:

https://partner.nordax.com/DSOP/v1

**Comment by stigbd** [comment]
Då har endepunktet blitt registrert. Vil dukke opp snarlig i produksjonsmiljøet.
