### ISSUE TITLE
Endepunkt for BRAbankASA i produksjonsmiljø

### ISSUE THREAD

**Issue by oysteinrodsjo** [Informasjonsforvaltning/dsop-api-spesifikasjoner#21]
Hei.

Kan dere registrere følgende endepunkt for BRAbank ASA - org.nr 913460715 i produksjonsmiljø?:

https://externalcontrolapi.bralabs.no/v1

Med vennlig hilsen,
Øystein

**Comment by stigbd** [comment]
Lagt til produksjons endepunkt i ad5becd
Vil kome på plass når indeksen oppdaterer seg i løpet av dagen.

**Comment by oysteinrodsjo** [comment]
Hei.

Det har kommet et ønske om korrigering til følgende endepunkt i produksjon:
https://externalcontrolapi.brabank.no/v1

Mvh,
Øystein
