### ISSUE TITLE
Nytt org.nr for Brabank

### ISSUE THREAD

**Issue by tonjelund** [Informasjonsforvaltning/dsop-api-spesifikasjoner#23]
Hei

Brabank ASA har fusjonert med en annen bank og har dermed skiftet org.nr.
Endepunktet for Brabank ASA er det samme som før, men kan dere oppdatere Brabank sitt org.nr til 986144706?

Vennlig hilsen 
Tonje Falch Lund

**Comment by tonjelund** [comment]
Hei, er dette rettet enda?

Vennlig hilsen
Tonje Falch Lund

**Comment by stigbd** [comment]
Beklager at det har tatt tid. Vi jobbar med denne tjenesten og forsøker å gjere rettinga i den forbindelse. Får det på plass til mandag.

**Comment by stigbd** [comment]
Etter å endeleg å satt på lufta ny implementasjon av tjenesten, er orgnummeret til Brabank no endra.
