### ISSUE TITLE
Endepunkt for TF Bank Norge i testmiljø.

### ISSUE THREAD

**Issue by Kristoffer-bits** [Informasjonsforvaltning/dsop-api-spesifikasjoner#26]
Navn: TF Bank Norge
Organisasjonsnummer: 923 194 592

Endepunkt for testmiljø: https://artemisapitest.tfbank.se/bits/v1/

**Comment by stigbd** [comment]
Då skal denne vere inne. Beklager at det har tatt lang tid:
https://demo.fellesdatakatalog.digdir.no/dataservices/a0340a67-a48d-3e92-8c25-e2966989f95f
