### ISSUE TITLE
Legge til endepunkt i produksjonsmiljø - Sparebank 1 Helgeland

### ISSUE THREAD

**Issue by tonjelund** [Informasjonsforvaltning/dsop-api-spesifikasjoner#27]
Hei,
Kan dere tilgjengeliggjøre endepunktet for Sparebank 1 Helgeland - 937904029 i produksjonsmiljø?

Endepunkt: 
https://api.sparebank1.no/dsopaccountcontrolinfo/v2/AccountControlInfoService/v2/937904029

**Comment by stigbd** [comment]
Helgeland har allereie eit endpunkt i produksjonsmiljø, ref https://data.norge.no/dataservices/f8e83a1f-6475-35db-ae4f-3df4d54a9902

Vil de at vi erstatter det som fins med endepunktet i kommentaren over?

**Comment by stigbd** [comment]
Er no i orden. Verifiser ved feks:
```
% curl -H "Accept: application/json" "https://fellesdatakatalog.digdir.no/api/apis/endpoints?serviceType=Kontoopplysninger&orgNos=937904029&environment=production" | jq
{
  "endpoints": [
    {
      "orgNo": "937904029",
      "serviceType": "Kontoopplysninger",
      "url": "https://api.sparebank1.no/dsopaccountcontrolinfo/v2/AccountControlInfoService/v2/937904029",
      "transportProfile": "eOppslag",
      "environment": "production"
    }
  ],
  "total": 1
}
