### ISSUE TITLE
Endepunkt for Sparebank 1 finans Østlandet

### ISSUE THREAD

**Issue by Tubaal** [Informasjonsforvaltning/dsop-api-spesifikasjoner#29]
Endepunkt skal registreres for: 

1. Navn: Sparebank 1 Finans Østlandet AS
2. Org.nr.: 975 963 748
3. Endepunkt i produksjonsmiljø: https://api.sparebank1.no

**Comment by Tubaal** [comment]
Rettelse på endepunkt: https://api.sparebank1.no/dsopaccountcontrolinfo/v2/AccountControlInfoService/v2/938521549

**Comment by stigbd** [comment]
Vi må avvente et nytt sertifikat før dette blir prodsatt. Forventer at det er på plass i løpet av et par dager.

**Comment by stigbd** [comment]
Er på plass no:
https://data.norge.no/dataservices/43d12bb9-2986-3f03-bd20-da721420b851
