### ISSUE TITLE
Endepunkt for Sparebank 1 Finans Midt- Norge

### ISSUE THREAD

**Issue by Tubaal** [Informasjonsforvaltning/dsop-api-spesifikasjoner#30]
Endepunkt skal registreres for:

Navn: Sparebank 1 Finans Midt Norge AS
Org.nr.: 938 521 549
Endepunkt i produksjonsmiljø: https://api.sparebank1.no/

**Comment by Tubaal** [comment]
Rettelse på endepunkt: https://api.sparebank1.no/dsopaccountcontrolinfo/v2/AccountControlInfoService/v2/938521549

**Comment by stigbd** [comment]
Vi må avvente et nytt sertifikat før dette blir prodsatt. Forventer at det er på plass i løpet av et par dager.

**Comment by stigbd** [comment]
Er på plass no:
https://data.norge.no/dataservices/f5b21f23-3f52-3d11-9b44-8651ea430365
