### ISSUE TITLE
Endepunkt for Sparebank 1 SR-Bank

### ISSUE THREAD

**Issue by Tubaal** [Informasjonsforvaltning/dsop-api-spesifikasjoner#33]
Endepunkt skal registreres for:

Navn: SPAREBANK 1 SR-BANK ASA
Org.nr.: 937 895 321
Endepunkt i produksjonsmiljø: 
https://api.sparebank1.no/dsopaccountcontrolinfo/v2/AccountControlInfoService/v2/937895321

Mvh
Tuba ALi

**Comment by stigbd** [comment]
Merk at SR-Bank hadde en oppføring i test- og produksjon frå før. Eg har fjerna dei gamle og lagt inn den nye slik det er spekka i dette issuet.

**Comment by stigbd** [comment]
Gjeldande oppføring er her:
https://data.norge.no/dataservices/c192e1c1-0db9-390f-8153-b53024ba7412

**Comment by Tubaal** [comment]
Var det gamle endepunktet ulikt det nye endepunktet? 
Om så, må endepunktet reverseres tilbake til det gamle endepunktet.

**Comment by stigbd** [comment]
Det gamle endepunktet i prod var:
`https://api.sparebank1.no/dsopaccountcontrolinfo/v2/AccountControlInfoService/v2/937895321`

Som er likte det nye. 

I den gamle oppføringa var også følgande test-endepunkt med:
`https://api-test.sparebank1.no/dsopaccountcontrolinfo/v2/AccountControlInfoService/v2/937895321`

Dette er no borte.
