### ISSUE TITLE
Endepunkt for Sparebank 1 Finans Nord-Norge

### ISSUE THREAD

**Issue by Tubaal** [Informasjonsforvaltning/dsop-api-spesifikasjoner#35]
Hei,

Endepunkt skal registreres for:

Navn: Sparebank 1 Finans Nord-Norge AS
Org.nr.: 930 050 237
Endepunkt i produksjonsmiljø: https://api.sparebank1.no/dsopaccountcontrolinfo/v2/AccountControlInfoService/v2/930050237

**Comment by stigbd** [comment]
Da er dette endepunktet definert i API-katalogen produksjonsmiljø:
https://data.norge.no/dataservices/24cb66ba-8052-3552-92f9-fb55b8e34848
