### ISSUE TITLE
Flere endepunkter

### ISSUE THREAD

**Issue by tonjelund** [Informasjonsforvaltning/dsop-api-spesifikasjoner#36]
Hei!
Dette er kun et spørsmål og ikke nødvendigvis en henvendelse for å gjennomføre det.
Vi lurer på om det er mulig i API-katalogen å registrere to endepunkter på en bank, dersom banken ønsker det? Dvs. at når det deretter gjøres oppslag på den konkrete banken i API-katalogen, så returneres alltid begge endepunktene.

**Comment by stigbd** [comment]
Slik datamodellen er no, vil det resultere i to oppføringar i API-katalogen, sidan det er endepunktet som er unik indentifikator for et API. Og konsumenten vil få to treff når dei søker etter produksjons-endepunkt for gitt bank (orgnummer). Dette er jo fult mogleg og ikkje spesielt omfattande, vil eg tru. Men det er antagelegvis ei "breaking change" og krever derfor styrt prosess og grundig testing.

**Comment by tonjelund** [comment]
Den er god, takk for forklaring. Ift. breaking change og testing, menes det da testing på deres ende eller testing av etatene som er de som i vårt tilfelle slår opp i API-katalogen for å få bankenes endepunkter?

**Comment by stigbd** [comment]
> Ift. breaking change og testing, menes det da testing på deres ende eller testing av etatene som er de som i vårt tilfelle slår opp i API-katalogen for å få bankenes endepunkter?

Begge deler. Men viktigast å teste frå etats-sida.

**Comment by tonjelund** [comment]
Den er god, takk!
