### ISSUE TITLE
Endepunkt for Sparebank 1 Kreditt i testmiljø. 

### ISSUE THREAD

**Issue by HildeThoresen** [Informasjonsforvaltning/dsop-api-spesifikasjoner#38]
Navn på finansforetaket: SPAREBANK 1 KREDITT AS

Organisasjonsnummer: 975 966 453

Endepunkt for testmiljø https://api-test.sparebank1.no//dsopaccountcontrolinfo/v2/AccountControlInfoService/v2/{orgnoBank}/

**Comment by NilsOveTen** [comment]
@HildeThoresen 
Hvis jeg følger formatet på de andre fra Sparebank 1 så blir test-endepunktet her `https://api-test.sparebank1.no/dsopaccountcontrolinfo/v2/AccountControlInfoService/v2/975966453`, er det korrekt?

Og jeg skal ikke opprette med produksjon-endepunkt, kun test?

**Comment by tonjelund** [comment]
Hei, det er korrekt. Også riktig at det kun er endepunktet for test foreløpig.
