### ISSUE TITLE
URL for å hente endepunkter i test

### ISSUE THREAD

**Issue by tonjelund** [Informasjonsforvaltning/dsop-api-spesifikasjoner#45]
Hei

Vi har en ny etat som skal ta Kontrollinformasjon i bruk, og trenger derfor å kunne kjøre oppslag mot API-katalogen for å hente ut endepunktene som er registrert på bankene i test.

Hva er url til API-katalogen som etatene bruker for å gjøre oppslag i test?

**Comment by NilsOveTen** [comment]
Vi har to som vil fungere, men `https://demo.fellesdatakatalog.digdir.no/endpoints?environment=test&serviceType=Kontoopplysninger` er nok det beste å oppgi.

Det andre er `https://staging.fellesdatakatalog.digdir.no/endpoints?environment=test&serviceType=Kontoopplysninger` som baserer seg på et mer flytende testmiljø, og har litt større sjangs for nedetid.

**Comment by tonjelund** [comment]
Det er i orden, da oppgir jeg det første. Takk for raskt svar.

**Comment by tonjelund** [comment]
Hei igjen

Når vi rapporterer inn banker med endepunkter for test, legges ikke test-endepunktene inn i testmiljøet?  (eller demo-miljøet som du nevnte over). Fikk en henvendelse fra en etat som sa at Nordea sitt endepunkt ikke lå inne i test.

**Comment by NilsOveTen** [comment]
Hentet ut lista med test-endepunkter nå, der ligger denne:
```
{
    "orgNo": "920058817",
    "serviceType": "Kontoopplysninger",
    "url": "https://RB-DSOP-ARC642-NO-test01-extranet.test.nordea.com:9040/v1",
    "transportProfile": "eOppslag",
    "environment": "test"
}
```

Er det noe feil med opplysningene der?

**Comment by tonjelund** [comment]
Sjekker opp med etaten om de kanskje gjorde en feil i oppslaget.

**Comment by NilsOveTen** [comment]
> Hm det var rart, det ser riktig ut. Og dette skal være returen når det gjøres oppslag i https://demo.fellesdatakatalog.digdir.no/endpoints?environment=test&serviceType=Kontoopplysninger ?

Var derfra jeg hentet det, ja

**Comment by NilsOveTen** [comment]
@tonjelund Kan jeg lukke denne?

**Comment by tonjelund** [comment]
@NilsOveTen Ja, takk.
