### ISSUE TITLE
Oppdatert endepunkt for Sbanken i produksjon

### ISSUE THREAD

**Issue by tonjelund** [Informasjonsforvaltning/dsop-api-spesifikasjoner#47]
Hei

Sbanken (org.nr. 915287700) trenger nå å oppdatere sitt endepunkt i produksjon også.
Nytt endepunkt: https://dsop.sbanken.no/api/v1

Fint om dere bekrefter når det er gjort.

Mvh
Tonje Lund

**Comment by NilsOveTen** [comment]
@tonjelund Dette er oppdatert nå
