### ISSUE TITLE
Endepunkt for Resurs Bank AB i testmiljø.

### ISSUE THREAD

**Issue by niddaaslam** [Informasjonsforvaltning/dsop-api-spesifikasjoner#49]
Hei,

Endepunkt skal registreres for:
Navn: Resurs bank AB  
Org.nr: 984150865
Endepunkt for testmiljø:  https://apigw-integration.test.resurs.loc/api/dsop_account_service

**Comment by NilsOveTen** [comment]
@niddaaslam `https://demo.fellesdatakatalog.digdir.no/endpoints?environment=test&serviceType=Kontoopplysninger` er nå oppdatert med testmiljøet til Resurs Bank
