### ISSUE TITLE
Navn i API katalog - Romerike Sparebank

### ISSUE THREAD

**Issue by niddaaslam** [Informasjonsforvaltning/dsop-api-spesifikasjoner#50]
Hei,

Navnet i API-katalogen skal endres fra Lillestrøm Sparebank til Romerike Sparebank.

[Accounts API Lillestrøm Sparebank](https://data.norge.no/dataservices/7c9b9b0c-a9d0-3908-bde5-fb6b030c4aaf)

**Comment by NilsOveTen** [comment]
@niddaaslam  [data norge](https://data.norge.no/dataservices/7c9b9b0c-a9d0-3908-bde5-fb6b030c4aaf) er nå oppdatert med nytt navn
