### ISSUE TITLE
Fjerne endepunkter til Eika banker. Tidspunkt for fjerning: 19.02.

### ISSUE THREAD

**Issue by niddaaslam** [Informasjonsforvaltning/dsop-api-spesifikasjoner#51]
Hei,

Følgende Eika-bankene flyttes over til TietoEvry i helgen 17.-19. februar. De vil knyttes til Konkursvarsel og vil ikke lenger ha kontrollinformasjon-API fra SDC. Endepunktene skal **_ikke_** fjernes før 19.02. Vi vil registrere nye endepunkter når bankene er klare med det.

**Eikabank pulje 2**			                                           Go Live
JERNBANEPERSONALETS SPAREBANK	     982719445		19.02.2023
HEMNE SPAREBANK	                             937902174		19.02.2023
RINDAL SPAREBANK	                             937900953		19.02.2023
SPAREBANKEN NARVIK	                             937903979		19.02.2023
OPDALS SPAREBANK	                             937901569		19.02.2023
SUNNDAL SPAREBANK	                             937899963		19.02.2023
ORKLA SPAREBANK	                             947278770		19.02.2023
TYSNES SPAREBANK                       	     937897375		19.02.2023

**Comment by KjerstiSteien** [comment]
Er det riktig forstått at disse endepunktene ønskes fjernet den 19.02.? Eller skal vi vente på beskjed om at nye endepunkt er klare før vi fjerner de gamle endepunktene?

**Comment by niddaaslam** [comment]
Hei,

Vi vet ikke når vi mottar de nye endepunktene, men Eika skal sende de over før den 19.februar.
Vi kan sende en bekreftelse dagen før de gamle endepunktene skal slettes.

Nidda Aslam
Tlf: +47 45497159

Fra: KjerstiSteien ***@***.***>
Sendt: mandag 6. februar 2023 12:23
Til: Informasjonsforvaltning/dsop-api-spesifikasjoner ***@***.***>
Kopi: Nidda Aslam ***@***.***>; Author ***@***.***>
Emne: Re: [Informasjonsforvaltning/dsop-api-spesifikasjoner] Fjerne endepunkter til Eika banker (Issue #51)


Er det riktig forstått at disse endepunktene ønskes fjernet den 19.02.? Eller skal vi vente på beskjed om at nye endepunkt er klare før vi fjerner de gamle endepunktene?

**Comment by KjerstiSteien** [comment]
Topp! Da avventer vi nærmere beskjed fra dere.

**Comment by NilsOveTen** [comment]
@niddaaslam alle de 8 nevnte bankene har nå blitt fjerna
