### ISSUE TITLE
Registrere endepunkter i API-katalogen: BANK NORWEGIAN, EN FILIAL AV NORDAX BANK AB (PUBL)

### ISSUE THREAD

**Issue by tonjelund** [Informasjonsforvaltning/dsop-api-spesifikasjoner#57]
Hei

Viser til tidligere sak #43.
Bankene (Nordax og Bank Norwegian) er ferdig fusjonert og skal innrapporteres i API-katalogen igjen, både i test og prod.

Bankens org.nr: 916573154 
Bankens navn: BANK NORWEGIAN, EN FILIAL AV NORDAX BANK AB (PUBL)
Endepunkt test: https://partner.preprod.nordax.com/DSOP/v1 
Endepunkt prod: https://partner.nordax.com/DSOP/v1

**Comment by NilsOveTen** [comment]
@tonjelund Nei, denne har nok dessverre ikke blitt gjort enda. Jeg skal få fiksa det i morgen

**Comment by NilsOveTen** [comment]
@tonjelund Dette har nå blitt oppdatert i både test og produksjon

**Comment by tonjelund** [comment]
Fint, takk
