### ISSUE TITLE
Navn i API katalog - Østre Agder Sparebank

### ISSUE THREAD

**Issue by niddaaslam** [Informasjonsforvaltning/dsop-api-spesifikasjoner#58]
Hei,

Navnet i API-katalogen skal endres fra Østre Agder sparebank til Agder sparebank den 18.3.2023 (teknisk fusjon).

https://data.norge.no/dataservices/9bdcba58-6f1c-3529-aba5-dcb67d0e87c1).

**Comment by NilsOveTen** [comment]
[data norge](https://data.norge.no/dataservices/9bdcba58-6f1c-3529-aba5-dcb67d0e87c1) har nå blitt oppdatert med korrekt navn
