### ISSUE TITLE
Endepunkt for Kredd i produksjonsmiljø

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/dsop-api-spesifikasjoner#6]
Endepunktet for Kredd AS – 917135428 kan registreres i produksjonsmiljø:
https://api.kredd.it/kok/v1

**Comment by stigbd** [comment]
Utført i d362ebd5a790a30e2732e160b4e977cec27d22a6

**Comment by thorejoa** [comment]
@stigbd Hei! Kan endepunktet fjernes fra produksjonsmiljø inntil videre? Eller skal jeg opprette det som egen issue?

**Comment by thorejoa** [comment]
@stigbd Hei igjen Stig! Se bort ifra forrige kommentar - endepunktet skal være registrert i produksjon. Beklager bryderiet!

**Comment by stigbd** [comment]
Den er grei. (Det beste er å opne egne issues, forøvrig.)
