### ISSUE TITLE
Endepunkt for Instabank i produksjonsmiljø

### ISSUE THREAD

**Issue by astridbits** [Informasjonsforvaltning/dsop-api-spesifikasjoner#60]
Instabank ASA
Org.nr. 816 914 582
endepunkt: https://central.services.banqsoft.com/dsop-kontroll/v1/

De bruker en leverandør: Banqsoft AS, org nr 871 579 792

**Comment by astridbits** [comment]
Skal endepunktsURL også bli oppdatert automatisk her: https://data.norge.no/dataservices/eb44639b-0d45-3d7a-b78f-831d3eb41f19 ? Ser at det har blitt oppdatert i endepunktsbeskrivelse.

**Comment by hegeaal** [comment]
Har vist blitt opprettet en ny id, skal fikse det nå:-) @astridbits

**Comment by hegeaal** [comment]
Nå er det fikset @astridbits!

**Comment by astridbits** [comment]
Flott, takk!
