### ISSUE TITLE
Endepunkt for Instabank i testmiljø

### ISSUE THREAD

**Issue by astridbits** [Informasjonsforvaltning/dsop-api-spesifikasjoner#61]
Instabank ASA
Org.nr. 816 914 582
endepunkt for testmiljø: https://central.services-test.banqsoft.com/dsopkontroll/v1

De bruker en leverandør: Banqsoft AS, org nr 871 579 792

**Comment by hegeaal** [comment]
Alt skal være oppdatert nå @astridbits :-)

**Comment by astridbits** [comment]
Takk!
