### ISSUE TITLE
Navneendring Komplett Bank ASA

### ISSUE THREAD

**Issue by astridbits** [Informasjonsforvaltning/dsop-api-spesifikasjoner#63]
Hei,
Komplett Bank ASA med organisasjonsnummer 998 997 801 endrer navn til Morrow Bank ASA i dag 25.04.2023.

**Comment by terjesyl** [comment]
@astridbits Er endepunktet det samme som før, https://eoppslag.online.komplettbank.no/v1,https://eoppslag.onlineservices.komplettbank.no/pp/v1 ?

**Comment by astridbits** [comment]
@terjesyl Banken sier: "Endepunktene er nå de samme, men vil bli endret innen utgangen av april 2024. Navn på nye endepunkt og tidspunkt er ikke avklart."
Vi lager en ny sak når de endrer endepunktene.

**Comment by terjesyl** [comment]
@astridbits 
Da er navnet endret i [produksjon](https://data.norge.no/dataservices/98229af7-5b4b-30ec-b569-8ffb0d37989e) og [demo-miljø](https://demo.fellesdatakatalog.digdir.no/dataservices/c6e505fb-d7b6-313a-9a97-86afd433b27e)

Vennlig hilsen Terje
