### ISSUE TITLE
Endepunkt for Sparebank 1 Kreditt i produksjonsmiljø

### ISSUE THREAD

**Issue by HildeThoresen** [Informasjonsforvaltning/dsop-api-spesifikasjoner#66]
Navn: Sparebank 1 Kreditt AS
Org. nr 975 966 453
Endepunkt i produksjonsmiljø: 
Endepunkt for produksjonsmiljø: 

https://api.sparebank1.no/dsopaccountcontrolinfo/v2/AccountControlInfoService/v2/975966453

**Comment by HildeThoresen** [comment]
Hei,
Riktig informasjon skal være 

For testmiljø: https://api-test.sparebank1.no/dsopaccountcontrolinfo/v2/AccountControlInfoService/v2/975966453
--
For prodmiljø: https://api.sparebank1.no/dsopaccountcontrolinfo/v2/AccountControlInfoService/v2/975966453

Jeg kan ikke se at vi tidligere har meldt inn noen url for prod, kun for test?

**Comment by NilsOveTen** [comment]
Det ser korrekt ut fra vi har av informasjon både i [produksjon](https://data.norge.no/dataservices/0748552e-c2d0-38f1-ae3d-f9d8aa738b03) og [test](https://demo.fellesdatakatalog.digdir.no/dataservices/1e33cc86-5a43-31ac-9b48-a4d13693637d)

Det ble lagt til på bakgrunn av dette issuet: #53

**Comment by HildeThoresen** [comment]
Flott! Takk for hjelpen!
