### ISSUE TITLE
Nytt endepunkt i produksjon

### ISSUE THREAD

**Issue by HildeThoresen** [Informasjonsforvaltning/dsop-api-spesifikasjoner#67]
Hei,
Følgende bank skal legges inn i api-katalogen produksjonsmiljø:
Melhus Sparebank
org.nr. 937901291

https://bf-esb-internet.edb.com/secesb/rest/era-dsop/v1/4239

**Comment by astridbits** [comment]
Hei, er det fremgang i denne saken?

**Comment by NilsOveTen** [comment]
Da er alt oppdatert med ny produksjonsuri: https://data.norge.no/dataservices/54a40b36-7658-310e-94ab-8a246c163e15
