### ISSUE TITLE
Nye endepunkter for Eika-banker

### ISSUE THREAD

**Issue by astridbits** [Informasjonsforvaltning/dsop-api-spesifikasjoner#69]
Hei,
Vi har fått inn endringer på endepunkt for følgende Eika-banker:

Tech-orgid - Bank
1058 – Marker Sparebank
1144 – Trøgstad Sparebank
1284 – Høland og Setskog Sparebank
1314 – Strømmen Sparebank
1449 – JBF
1729 – Bien Sparebank
1839 – Grue Sparebank
1874 – Odal Sparebank
2355 – Skue Sparebank
2609 – Skagerrak Sparebank
3263 – Den Gule Banken, Sandnes Sparebank
3294 – Jæren Sparebank
3354 – Hjelmeland Sparebank
3528 – Tysnes Sparebank
4039 – Sunndal Sparebank
4113 – Rindal Sparebank
4269 – Oppdalsbanken
4274 – Orkla Sparebank
4299 – Bjugn Sparebank
4314 - Hemne Sparebank
4348 – Åfjord Sparebank
4354 – Haltdalen Sparebank
4478 – Hegra Sparebank
4529 – Sparebanken Narvik
9619 – Bank2
9815 - Sparesmart
1274 - Aurskog Sparebank
1459 - Oslofjord Sparebank
2059 - Totens Sparebank
2629 - Tinn Sparebank
2698 - HjartdalBanken
2903 - Evje og Hornnes Sparebank
4064 - Ørskog Sparebank
4076 - Romsdalsbanken
4284 - RørosBanken
4335 - Soknedal Sparebank

Nye endepunkt: https://bf-esb-internet.edb.com/secesb/rest/era-dsop/v1/<Tech-orgid>

Fint om dette kan bli gjort raskt.

**Comment by hegeaal** [comment]
@astridbits Hei! Tolker jeg det riktig at de nye endepunktene er https://bf-esb-internet.edb.com/secesb/rest/era-dsop/v1/{nummeret_til_banken}? Så f.eks. for _1058 – Marker Sparebank_ så er urlen https://bf-esb-internet.edb.com/secesb/rest/era-dsop/v1/1058?

**Comment by hegeaal** [comment]
@astridbits Vi trenger også orgnr. for alle bankene for å legge de til :-)

**Comment by astridbits** [comment]
@hegeaal Hei, ja det er riktig tolket! Ja, selvfølgelig, her er listen med orgnr. inkludert:

Tech-orgid - Bank - Org. nr.
1058 – Marker Sparebank - 937884672
1144 – Trøgstad Sparebank - 937885377
1284 – Høland og Setskog Sparebank - 937885822
1314 – Strømmen Sparebank - 937886160
1449 – JBF (Jernbanepersonalets sparebank) - 982719445
1729 – Bien Sparebank - 991853995
1839 – Grue Sparebank - 937886705
1874 – Odal Sparebank - 937887043
2355 – Skue Sparebank - 837889812
2609 – Skagerrak Sparebank - 937891245
3263 – Den Gule Banken, Sandnes Sparebank - 915691161
3294 – Jæren Sparebank - 937895976
3354 – Hjelmeland Sparebank - 937896581
3528 – Tysnes Sparebank - 937897375
4039 – Sunndal Sparebank - 937899963
4113 – Rindal Sparebank - 937900953
4269 – Oppdalsbanken - 937901569
4274 – Orkla Sparebank - 947278770
4299 – Bjugn Sparebank - 937902085
4314 - Hemne Sparebank(Trøndelag Sparebank) - 937902174
4348 – Åfjord Sparebank - fusjonert inn i Hemne, utdatert informasjon fra Eika
4354 – Haltdalen Sparebank - 837902622
4478 – Hegra Sparebank - 937903235
4529 – Sparebanken Narvik - 937903979
9619 – Bank2 - 988257133
9815 - Sparesmart (En del av Eika Kredittbank) - 989997254
1274 - Aurskog Sparebank - 937885644
1459 - Oslofjord Sparebank - 985750378
2059 - Totens Sparebank - 937887787
2629 - Tinn Sparebank - 937891423
2698 - HjartdalBanken (Hjartdal og Gransherad Sparebank) - 937893299
2903 - Evje og Hornnes Sparebank - 937894171
4064 - Ørskog Sparebank - 837900212
4076 - Romsdalsbanken (Romsdalen Sparebank) - 937900775
4284 - RørosBanken - 956548888
4335 - Soknedal Sparebank - 937902263

**Comment by hegeaal** [comment]
Flott, takk!

**Comment by hegeaal** [comment]
@astridbits Hva vil du at vi skal gjøre med denne? 

> 4348 – Åfjord Sparebank - fusjonert inn i Hemne, utdatert informasjon fra Eika

**Comment by astridbits** [comment]
@hegeaal det ser ut som denne banken allerede er oppdatert i API-katalogen, så dere trenger ikke gjøre noe med den :)

**Comment by astridbits** [comment]
Hei, siden saken er closed, er endringene pushet ut eller skjer det senere? Ser ikke de nye endepunktene i API katalogen ennå

**Comment by hegeaal** [comment]
@astridbits Det skal være på plass nå! Saken ble lukket når vi oppdaterte selve katalogen, men endringene ble ikke synlige før høstingen som skjedde 11.00  :-)

**Comment by astridbits** [comment]
@hegeaal Flott, takk!
