### ISSUE TITLE
Nye endepunkter for Eikabanker

### ISSUE THREAD

**Issue by HildeThoresen** [Informasjonsforvaltning/dsop-api-spesifikasjoner#72]
Hei,
Det er nye endepunkter for disse bankene:

**Bankens navn | Tech.orgid**

Eidsberg Sparebank | 1028
Berg Sparebank | 1109
Etnedal Sparebank | 2142
Valdres Sparebank | 2149
Andebu Sparebank | 2504
Larvikbanken | 2514
Birkenes Sparebank | 2884
Sogn Sparebank | 3839
Grong Sparebank | 4454
Vekselbanken | 9588

Nytt endepunkt er https://bf-esb-internet.edb.com/secesb/rest/era-dsop/v1/<Tech-orgid>
Eksempelvis blir Eidsberg Sparebank sitt endepunkt https://bf-esb-internet.edb.com/secesb/rest/era-dsop/v1/1028

**Comment by HildeThoresen** [comment]
Bankenes nye endepunkter vil gjelde fra mandag morgen 11.september.

**Comment by HildeThoresen** [comment]
Ser at ekempelet jeg har fitt for Eidsberg Sparebank er riktig, men at linjen ovenfor mangler/Tehc.orgID. Håper det likevel er forståelig ut ifra eksemplet :) Riktig struktur er da 

 https://bf-esb-internet.edb.com/secesb/rest/era-dsop/v1/Tech.orgID

**Comment by jeffreiffers** [comment]
Vekselbanken finnes ikke i vår oversikt. Hva er organisasjonsnummeret?

**Comment by HildeThoresen** [comment]
Hei,
Ser at Eika ikke skrev navnet det er registrert i Brønnøysundregistyeret. 

Fullt navn: Voss Veksel- og Landmandsbank ASA
Org. nr. 817 244 742

Beklager det!

**Comment by jeffreiffers** [comment]
@HildeThoresen Endringene er prodsatt i dag tidlig.
