### ISSUE TITLE
Fusjon Sparebank 1 SMN og Sparebank 1 Søre Sunnmøre

### ISSUE THREAD

**Issue by HildeThoresen** [Informasjonsforvaltning/dsop-api-spesifikasjoner#77]
Sparebank 1 SMN og Sparebank 1 Søre Sunnmøre har teknisk fusjon denne helgen. Ønsker dere at jeg sender en melding og sier ifra om dette, eller har dere en annen rutine for fusjonering av endepunkter hos dere? 

SpareBank 1 SMN (937901003) og SpareBank 1 Søre Sunnmøre (937899785) 
SpareBank 1 SMN er overtakende bank og beholder derfor navn og organisasjonsnummer. 

Sparebank 1 Søre Sunnmøre skal derfor fjernes fra API-katalogen.

**Comment by NilsOveTen** [comment]
> Sparebank 1 SMN og Sparebank 1 Søre Sunnmøre har teknisk fusjon denne helgen. Ønsker dere at jeg sender en melding og sier ifra om dette, eller har dere en annen rutine for fusjonering av endepunkter hos dere?

Vår rutine er at alle endringer av API-katalogen kommer gjennom issues her

**Comment by NilsOveTen** [comment]
@HildeThoresen Vi har nå fått fjerna Sparebank 1 Søre Sunnmøre fra API-katalogen
