### ISSUE TITLE
Registrering av Resurs Bank i API-katalogen 

### ISSUE THREAD

**Issue by HildeThoresen** [Informasjonsforvaltning/dsop-api-spesifikasjoner#79]
Hei,
Resurs Bank skal registreres i API-katalogen. 

Org. nr.  984 150 865
Navn: RESURS BANK AB
Endepunkt test: https://apigw-integration.test.resurs.loc/api/dsop_account_service

**Comment by valosnah** [comment]
Hei

https://demo.fellesdatakatalog.digdir.no/endpoints?environment=test&serviceType=Kontoopplysninger&orgNos=984150865

`````{
    "endpoints": [
        {
            "orgNo": "984150865",
            "serviceType": "Kontoopplysninger",
            "url": "https://apigw-integration.test.resurs.loc/api/dsop_account_service",
            "transportProfile": "eOppslag",
            "environment": "test"
        }
    ],
    "total": 1
}
`````
Det ser ut som denne allerede er registrert? 
Ser ut til å ha ligget inne siden februar i år.

**Comment by HildeThoresen** [comment]
Hei,
Burde jeg kunne se den når jeg søker opp i Felles Datakatalog, eller dukker det ikke opp før vi gir endepunktet for prod? Jeg greier ikke å se den når jeg søker den opp, nemlig.

**Comment by HildeThoresen** [comment]
Fikk du undersøkt om du kan se den i felles datakatalog?

**Comment by valosnah** [comment]
Hei, beklager tregt svar.
Nei, vi legger den ikke inn i produksjon før vi har et endepunkt for prod.
