### ISSUE TITLE
Nye endepunkter for Eikabanker - prodsettes 23. oktober

### ISSUE THREAD

**Issue by HildeThoresen** [Informasjonsforvaltning/dsop-api-spesifikasjoner#80]
Hei,
5 nye banker endret endepunkt på morgenen den 23. oktober. Endepunktene kan registreres fra 07:00 og utover på mandagen. 

Navn: Romerike Sparebank
Org. nr 937885911 
Endepunkt i produksjonsmiljø: https://bf-esb-internet.edb.com/secesb/rest/era-dsop/v1/1287

Navn: Valle Sparebank
Org. nr 937893922 
Endepunkt i produksjonsmiljø: https://bf-esb-internet.edb.com/secesb/rest/era-dsop/v1/2894

Navn: Agder Sparebank
Org. nr 937894260 
Endepunkt i produksjonsmiljø: https://bf-esb-internet.edb.com/secesb/rest/era-dsop/v1/2909

Navn: Kvinesdal Sparebank
Org. nr 937894805 
Endepunkt i produksjonsmiljø: https://bf-esb-internet.edb.com/secesb/rest/era-dsop/v1/3081

Navn: Gildeskål Sparebank
Org. nr 937904673 
Endepunkt i produksjonsmiljø: https://bf-esb-internet.edb.com/secesb/rest/era-dsop/v1/4611

**Comment by hegeaal** [comment]
Skal være i orden nå:-)
