### ISSUE TITLE
Legge til Volkswagen Møller Bilfinans i API-katalogen

### ISSUE THREAD

**Issue by HildeThoresen** [Informasjonsforvaltning/dsop-api-spesifikasjoner#85]
Hei,
Volkswagen Møller Bilfinans skal registreres i API-katalogen.

Org. nr. 992873183
Navn: Volkswagen Møller Bilfinans
Endepunkt prod: https://central.services.banqsoft.com/dsop-kontroll/v1/

De er klare nå :)

**Comment by KjerstiSteien** [comment]
Hvor mye haster dette? Vi må prioritere hardt før påske, så hvis dette kan vente til etter påske hadde det vært det beste for oss.

**Comment by HildeThoresen** [comment]
Haster litt, dessverre! Vanligvis prøver vi å skrive det så raskt vi vet, men nå kom det dessverre brått.

**Comment by NilsOveTen** [comment]
@HildeThoresen Det er korrekt at denne skal ha nøyaktig samme prod-endepunkt som 816914582 - Instabank ASA?

**Comment by HildeThoresen** [comment]
Hei,
Jeg må sjekke opp med dem. Det virker rart.

Hilde Thoresen
Tlf: +47 994 29 560

Fra: Nils Ove Tendenes ***@***.***>
Sendt: søndag 24. mars 2024 17:49
Til: Informasjonsforvaltning/dsop-api-spesifikasjoner ***@***.***>
Kopi: Hilde Thoresen ***@***.***>; Mention ***@***.***>
Emne: Re: [Informasjonsforvaltning/dsop-api-spesifikasjoner] Legge til Volkswagen Møller Bilfinans i API-katalogen (Issue #85)


@HildeThoresen<https://github.com/HildeThoresen> Det er korrekt at denne skal ha nøyaktig samme prod-endepunkt som 816914582 - Instabank ASA?

**Comment by HildeThoresen** [comment]
Hei,
Fikk svar fra dem nå: Det stemmer at de skal ha samme endepunkt. Limer inn svaret for ordens skyld:

Spurte Banqsoft også om det samme tidligere, og da fikk jeg dette til svar:
Vi har en multi-tennant tjeneste, slik at alle våre kunder får samme endepunkt i den oversikten, og det er denne som vi sendte tidligere: https://central.services.banqsoft.com/dsop-kontroll/v1/

Hilde Thoresen
Tlf: +47 994 29 560

Fra: Hilde Thoresen
Sendt: mandag 25. mars 2024 09:21
Til: 'Informasjonsforvaltning/dsop-api-spesifikasjoner' ***@***.***>
Emne: SV: [Informasjonsforvaltning/dsop-api-spesifikasjoner] Legge til Volkswagen Møller Bilfinans i API-katalogen (Issue #85)

Hei,
Jeg må sjekke opp med dem. Det virker rart.

Hilde Thoresen
Tlf: +47 994 29 560

Fra: Nils Ove Tendenes ***@***.******@***.***>>
Sendt: søndag 24. mars 2024 17:49
Til: Informasjonsforvaltning/dsop-api-spesifikasjoner ***@***.******@***.***>>
Kopi: Hilde Thoresen ***@***.******@***.***>>; Mention ***@***.******@***.***>>
Emne: Re: [Informasjonsforvaltning/dsop-api-spesifikasjoner] Legge til Volkswagen Møller Bilfinans i API-katalogen (Issue #85)


@HildeThoresen<https://github.com/HildeThoresen> Det er korrekt at denne skal ha nøyaktig samme prod-endepunkt som 816914582 - Instabank ASA?

**Comment by NilsOveTen** [comment]
@HildeThoresen Den er ute i prod hos oss nå
