### ISSUE TITLE
Endepunkt for Oslo pensjonsforsikring AS i produksjonsmiljø.  

### ISSUE THREAD

**Issue by niddaaslam** [Informasjonsforvaltning/dsop-api-spesifikasjoner#94]
Hei,

Oslo Pensjonsforsikring AS skal registreres i API Katalogen. (vi har allerede sendt inn en sak angående test #92)

Org. nr: 982759412
Navn: Oslo Pensjonsforsikring AS
Endepunkt for produksjonsmiljø: https://dsop.core.kassa.no:8443/api/v2/

**Comment by NilsOveTen** [comment]
https://data.norge.no/data-services/9b5137ad-8998-3666-83c1-097e68bb74e0
https://data.norge.no/endpoints?environment=production&serviceType=Kontoopplysninger&orgNos=982759412
