### ISSUE TITLE
Endring av test-endepunkt for Nordea i API-katalogen

### ISSUE THREAD

**Issue by astridbits** [Informasjonsforvaltning/dsop-api-spesifikasjoner#98]
Hei,
Nordea har endret endepunkts-URL i test til https://rb-dsop-arc642-no-test01-extranet.test.nordea.com:9040/v2 som skal registreres i API-katalogen

Org. nr.: 920058817
Navn: NORDEA BANK ABP, FILIAL I NORGE
Nytt endepunkt test: https://rb-dsop-arc642-no-test01-extranet.test.nordea.com:9040/v2

**Comment by terjesyl** [comment]
@astridbits da skal disse endringene være ute:)

https://demo.fellesdatakatalog.digdir.no/data-services/f47d82e4-054b-315d-a525-8cf82b3fc85b
